# Generated by Django 2.1.4 on 2019-02-16 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_number', models.CharField(max_length=250)),
                ('int_number', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=8)),
                ('stock_amount', models.BigIntegerField()),
                ('currently_produced', models.BigIntegerField()),
                ('price_per_piece', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('chem_name', models.CharField(max_length=250)),
                ('company', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Material'),
        ),
    ]
