# Generated by Django 2.1.4 on 2019-03-26 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20190327_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='currently_produced',
            field=models.BigIntegerField(verbose_name='In Produktion'),
        ),
        migrations.AlterField(
            model_name='article',
            name='ext_number',
            field=models.CharField(max_length=250, verbose_name='Ext. ID'),
        ),
        migrations.AlterField(
            model_name='article',
            name='int_number',
            field=models.CharField(max_length=250, verbose_name='Int. ID'),
        ),
        migrations.AlterField(
            model_name='article',
            name='price_per_piece',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preis'),
        ),
        migrations.AlterField(
            model_name='article',
            name='stock_amount',
            field=models.BigIntegerField(verbose_name='Lagerbestand'),
        ),
        migrations.AlterField(
            model_name='article',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Gewicht'),
        ),
        migrations.AlterField(
            model_name='material',
            name='chem_name',
            field=models.CharField(max_length=250, verbose_name='Tech. Name'),
        ),
        migrations.AlterField(
            model_name='material',
            name='company',
            field=models.CharField(max_length=250, verbose_name='Firma'),
        ),
    ]
