# Generated by Django 2.1.4 on 2019-03-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20190327_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='price_per_piece',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preis in €'),
        ),
    ]
