# Generated by Django 2.1.4 on 2019-04-02 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20190327_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nummernkreise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.BigIntegerField(default=19)),
                ('order_number', models.BigIntegerField(default=0)),
                ('task_number', models.BigIntegerField(default=0)),
                ('prod_number', models.BigIntegerField(default=0)),
                ('delivery_number', models.BigIntegerField(default=0)),
                ('invoice_number', models.BigIntegerField(default=0)),
            ],
        ),
    ]
