# Generated by Django 2.1.4 on 2019-04-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_nummernkreise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Kunde')),
                ('address', models.CharField(max_length=50, verbose_name='Adresse')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon')),
            ],
        ),
        migrations.CreateModel(
            name='MoldingMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Maschine')),
                ('power', models.BigIntegerField(default=0, verbose_name='Tonnen')),
                ('power_consumtion', models.BigIntegerField(default=0, verbose_name='Max. Stromverbrauch')),
                ('injection_unit_volume', models.BigIntegerField(default=0, verbose_name='Volumen in cm³')),
            ],
        ),
        migrations.CreateModel(
            name='Tooling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Wkz-Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='currently_produced',
        ),
        migrations.AddField(
            model_name='article',
            name='cavities',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='article',
            name='ext_number',
            field=models.CharField(max_length=50, verbose_name='Ext. ID'),
        ),
        migrations.AlterField(
            model_name='article',
            name='int_number',
            field=models.CharField(max_length=50, verbose_name='Int. ID'),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Artikel'),
        ),
        migrations.AlterField(
            model_name='article',
            name='stock_amount',
            field=models.BigIntegerField(default=0, verbose_name='Lagerbestand'),
        ),
        migrations.AlterField(
            model_name='material',
            name='chem_name',
            field=models.CharField(max_length=50, verbose_name='Tech. Name'),
        ),
        migrations.AlterField(
            model_name='material',
            name='company',
            field=models.CharField(max_length=50, verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='tooling',
            name='related_articles',
            field=models.ManyToManyField(to='stock.Article'),
        ),
        migrations.AddField(
            model_name='tooling',
            name='related_engines',
            field=models.ManyToManyField(to='stock.MoldingMachine'),
        ),
    ]
