# Generated by Django 2.1.4 on 2019-04-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('stock', '0006_auto_20190423_0008'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MoldingMachine',
            new_name='MouldingMachine',
        ),
        migrations.AlterField(
            model_name='article',
            name='cavities',
            field=models.BigIntegerField(default=1, verbose_name='Kavitäten'),
        ),
    ]
