# Generated by Django 2.1.4 on 2019-04-22 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20190423_0045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mouldingmachine',
            old_name='power_consumtion',
            new_name='power_consumption',
        ),
    ]
