# Generated by Django 2.2.7 on 2019-11-06 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_auto_20190427_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='stock_amount',
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_amount', models.BigIntegerField(default=0, verbose_name='Lagerbestand')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Article')),
            ],
        ),
    ]
