# Generated by Django 2.1.4 on 2019-03-29 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestellung', '0003_auto_20190326_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='collection',
            field=models.BooleanField(default=False, verbose_name='Sammelbestellung'),
        ),
        migrations.AddField(
            model_name='order',
            name='collection_name',
            field=models.CharField(default='Single', max_length=250, verbose_name='Bestellungsname'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.BigIntegerField(default=0, verbose_name='Bestellnummer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.BigIntegerField(default=0, verbose_name='Menge'),
        ),
    ]
