# Generated by Django 2.1.4 on 2019-04-03 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestellung', '0004_auto_20190329_0106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_number',
            new_name='order_number_int',
        ),
        migrations.AddField(
            model_name='order',
            name='order_number_ext',
            field=models.BigIntegerField(default=0, verbose_name='Bestellnummer'),
        ),
    ]
