# Generated by Django 2.1.4 on 2019-04-27 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_auto_20190427_1549'),
        ('bestellung', '0005_auto_20190403_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='company',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number_ext',
            field=models.BigIntegerField(default=0, verbose_name='Bestellnummer extern'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number_int',
            field=models.BigIntegerField(default=0, verbose_name='Bestellnummer intern'),
        ),
    ]
