# Generated by Django 2.2.7 on 2019-11-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestellung', '0007_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_amount',
            field=models.BigIntegerField(default=0, verbose_name='Menge'),
        ),
    ]
