# Generated by Django 2.2.7 on 2019-11-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestellung', '0011_auto_20191107_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(default='Bestellung', max_length=250, verbose_name='Status'),
        ),
    ]
