# Generated by Django 2.2.7 on 2019-11-26 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestellung', '0013_auto_20191107_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='production_starting_time',
            field=models.TimeField(default=datetime.time, verbose_name='Startzeit'),
        ),
    ]
