# Generated by Django 2.2.7 on 2019-11-26 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestellung', '0014_order_production_starting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='production_starting_time',
            field=models.TimeField(default=datetime.datetime, verbose_name='Startzeit'),
        ),
    ]
