# Generated by Django 2.2.7 on 2019-11-26 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestellung', '0015_auto_20191126_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='production_starting_time',
        ),
    ]
