# Generated by Django 2.2.7 on 2019-11-26 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestellung', '0016_remove_order_production_starting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Lieferdatum'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Bestelldatum'),
        ),
    ]
