# Generated by Django 2.2.7 on 2019-11-26 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestellung', '0017_auto_20191126_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='Lieferdatum'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime.today, verbose_name='Bestelldatum'),
        ),
    ]
