# Generated by Django 2.2.7 on 2020-01-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestellung', '0018_auto_20191126_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='marked_field',
            field=models.BooleanField(default=False),
        ),
    ]
