# Generated by Django 2.2.7 on 2020-01-28 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestellung', '0019_order_marked_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='marked_field',
        ),
    ]
