# Generated by Django 2.2.7 on 2019-11-06 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aktuelles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aktuelles',
            name='stock_amount',
        ),
    ]
