# Generated by Django 2.1.4 on 2019-05-01 23:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0009_auto_20190427_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auftragsobjekt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Lieferdatum')),
                ('runtime', models.BigIntegerField(default=1440, verbose_name='Laufzeit')),
                ('auftrags_kw', models.BigIntegerField(default=1440, verbose_name='Laufzeit')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Maschine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maschine_name', models.CharField(default='Maschine X', max_length=250, verbose_name='Maschine')),
                ('time_per_week', models.BigIntegerField(default=1440, verbose_name='Laufzeit')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Customer')),
            ],
        ),
    ]
