# Generated by Django 2.1.4 on 2019-05-13 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_auto_20190427_1549'),
        ('maschinenplanung', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auftragsobjekt',
            old_name='start_date',
            new_name='latest_finish',
        ),
        migrations.AddField(
            model_name='auftragsobjekt',
            name='aricle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock.Article'),
        ),
        migrations.AddField(
            model_name='auftragsobjekt',
            name='fixed_starting_time',
            field=models.BigIntegerField(default=1440, verbose_name='fStartzeit'),
        ),
        migrations.AddField(
            model_name='auftragsobjekt',
            name='prod_started',
            field=models.BooleanField(default=False, verbose_name='Already started'),
        ),
        migrations.AddField(
            model_name='auftragsobjekt',
            name='starting_time',
            field=models.BigIntegerField(default=1440, verbose_name='Startzeit'),
        ),
        migrations.AlterField(
            model_name='auftragsobjekt',
            name='name',
            field=models.CharField(default='Something', max_length=250, verbose_name='Auftragsobjekt'),
        ),
    ]
