# Generated by Django 2.1.4 on 2019-05-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maschinenplanung', '0002_auto_20190513_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auftragsobjekt',
            name='aricle',
        ),
        migrations.AddField(
            model_name='auftragsobjekt',
            name='article',
            field=models.CharField(default='Something:article', max_length=250, verbose_name='Auftragsobjekt'),
        ),
        migrations.AlterField(
            model_name='auftragsobjekt',
            name='name',
            field=models.CharField(default='Something_name', max_length=250, verbose_name='Auftragsobjekt'),
        ),
    ]
