# Generated by Django 2.2.7 on 2019-11-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maschinenplanung', '0003_auto_20190513_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auftragsobjekt',
            name='auftrags_kw',
            field=models.BigIntegerField(default=1440, verbose_name='Ziel KW'),
        ),
    ]
